name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

concurrency:
  group: pages-deployment
  cancel-in-progress: true

jobs:
  pages-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build your site
        run: |
          # Add your build steps here
          echo "Pretending to build..."
          mkdir -p dist
          echo "<h1>Hello World</h1>" > dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
