jobs:
  pages-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Retry Deployment on Conflict
        if: failure()
        run: |
          echo "Initial deployment failed. Waiting 30 seconds before retry..."
          sleep 30
          echo "Retrying deployment..."
          gh workflow run <workflow-file-name> --ref ${{ github.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
